#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="x86_64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

# Create and use a custom temp directory
export TMPDIR="$HOME/.nixbuild-tmp"
mkdir -p "$TMPDIR"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' \
    build \
    --impure \
    -vvvv \
    --show-trace \
    --option sandbox false \
    .#$FLAKE_SYSTEM $@

echo "${YELLOW}Switching to new generation...${NC}"
# Only use --impure once
./result/sw/bin/darwin-rebuild switch \
    --impure \
    --option sandbox false \
    --flake .#${SYSTEM_TYPE} $@

echo "${YELLOW}Cleaning up...${NC}"
rm -rf "$TMPDIR"
[ -L ./result ] && unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
